### PR TITLE
Plural name fix

### PR DESCRIPTION
**Pull request by Kingofthehill4965**
closes issue #310

### CODE REVIEW

**Comment by Buggem** [comment]
You dont know how to speak english

**Comment by Kingofthehill4965** [comment]
@Buggem ??

**Comment by Kingofthehill4965** [comment]
wdym

**Comment by ltzmax** [comment]
@Buggem
English is not everyone's first language. Please refrain from comments like this in PRs, we'll review them and correct it to correct when we're there.

**Comment by Buggem** [comment]
sorry if i was offensive or such. i was drunk and shouldnt have said that

**Comment by Kingofthehill4965** [comment]
i found a few more places where i gotta change it

**Pull request closed without merging**
