### PR TITLE
Add logging and optional command logging

### PR DESCRIPTION
**Pull request by flaree**
Add logging to admin commands

Optional command and catch logs

### CODE REVIEW

**Review by ltzmax — COMMENTED** [review]
Failed to start with this pr due to the below
```py
ballsdex-discordbot-bot-1              | Traceback (most recent call last):
ballsdex-discordbot-bot-1              |   File "<frozen runpy>", line 198, in _run_module_as_main
ballsdex-discordbot-bot-1              |   File "<frozen runpy>", line 88, in _run_code
ballsdex-discordbot-bot-1              |   File "/code/ballsdex/__main__.py", line 344, in <module>
ballsdex-discordbot-bot-1              |     main()
ballsdex-discordbot-bot-1              |   File "/code/ballsdex/__main__.py", line 260, in main
ballsdex-discordbot-bot-1              |     read_settings(cli_flags.config_file)
ballsdex-discordbot-bot-1              |   File "/code/ballsdex/settings.py", line 110, in read_settings
ballsdex-discordbot-bot-1              |     settings.log_channel = content["log-channel"]
ballsdex-discordbot-bot-1              |                            ~~~~~~~^^^^^^^^^^^^^^^
ballsdex-discordbot-bot-1              | KeyError: 'log-channel'
ballsdex-discordbot-bot-1 exited with code 1
```

**Review by ltzmax — CHANGES_REQUESTED** [review]
Everything seems to look fine, only one error to be fixed then it should be good.

**Comment by ErshamtunseCNR** [comment]
@ltzmax how i cant suggest

**Review by ltzmax — APPROVED** [review]
Good to go!

**Pull request merged**
