### PR TITLE
Add guild blacklisting + reword blacklist message

### PR DESCRIPTION
**Pull request by flaree**
Add guild blacklist
Reword blacklist message to include link to support server
Changed blacklist from list to set to increase perf

TODO:
Stop balls from spawning if in blacklisted servers
Generate migration code

Yet to be tested

### CODE REVIEW

**Review by ltzmax — COMMENTED** [review]
After some testing it mostly works, but there's a error message in logs when using example `/balls favorite countryball`, anything that has a `countryball` selection to see countryballs in the slash commands menu on blacklisted servers will show this below here:
```py
ballsdex-discordbot-bot-1              | 2023-05-23 15:50:12 CRITICAL ballsdex Caught unhandled exception in <Task finished name='CommandTree-invoker' coro=<CommandTree._from_interaction.<locals>.wrapper() done, defined at /usr/local/lib/python3.11/site-packages/discord/app_commands/tree.py:1087> exception=HTTPException('400 Bad Request (error code: 50035): Invalid Form Body\nIn type: Value must be one of {8}.')>:
ballsdex-discordbot-bot-1              | Task exception was never retrieved
ballsdex-discordbot-bot-1              | Traceback (most recent call last):
ballsdex-discordbot-bot-1              |   File "/usr/local/lib/python3.11/site-packages/discord/app_commands/tree.py", line 1089, in wrapper
ballsdex-discordbot-bot-1              |     await self._call(interaction)
ballsdex-discordbot-bot-1              |   File "/usr/local/lib/python3.11/site-packages/discord/app_commands/tree.py", line 1210, in _call
ballsdex-discordbot-bot-1              |     if not await self.interaction_check(interaction):
ballsdex-discordbot-bot-1              |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ballsdex-discordbot-bot-1              |   File "/code/ballsdex/core/bot.py", line 41, in interaction_check
ballsdex-discordbot-bot-1              |     return await bot.blacklist_check(interaction)
ballsdex-discordbot-bot-1              |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ballsdex-discordbot-bot-1              |   File "/code/ballsdex/core/bot.py", line 229, in blacklist_check
ballsdex-discordbot-bot-1              |     await interaction.response.send_message(
ballsdex-discordbot-bot-1              |   File "/usr/local/lib/python3.11/site-packages/discord/interactions.py", line 778, in send_message
ballsdex-discordbot-bot-1              |     await adapter.create_interaction_response(
ballsdex-discordbot-bot-1              |   File "/usr/local/lib/python3.11/site-packages/discord/webhook/async_.py", line 221, in request
ballsdex-discordbot-bot-1              |     raise HTTPException(response, data)
ballsdex-discordbot-bot-1              | discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
ballsdex-discordbot-bot-1              | In type: Value must be one of {8}.
```
Also with removing from blacklist:
```py
ballsdex-discordbot-bot-1              | Traceback (most recent call last):
ballsdex-discordbot-bot-1              |   File "/usr/local/lib/python3.11/site-packages/discord/app_commands/commands.py", line 841, in _do_call
ballsdex-discordbot-bot-1              |     return await self._callback(self.binding, interaction, **params)  # type: ignore
ballsdex-discordbot-bot-1              |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ballsdex-discordbot-bot-1              |   File "/code/ballsdex/packages/admin/cog.py", line 623, in blacklist_remove_guild
ballsdex-discordbot-bot-1              |     self.bot.blacklist.remove(guild.id)
ballsdex-discordbot-bot-1              | KeyError: 1109451676659752960
```
It removes from the blacklist but it tells this instead of `Guild is now removed from blacklist.`
Frail179b

**Comment by ASUSOmen** [comment]
Tried this yesterday and it completely broke blacklist, couldn't add, couldn't remove, and even b. commands were broken. Thankfully I fixed it before it became a big issue but it still needs work. Not criticizing it, just trying to give review.

**Comment by flaree** [comment]
> Tried this yesterday and it completely broke blacklist, couldn't add, couldn't remove, and even b. commands were broken. Thankfully I fixed it before it became a big issue but it still needs work. Not criticizing it, just trying to give review.

Yes, as Max mentioned above there's some issues. Whenever I have time it'll be looked at. As for it becoming a 'big issue', please do not run code in PRs unless you're absolutely sure it's going to work, especially on a production instance. Once they are tested by the team they are merged and are then would be considered safe to use.

**Comment by flaree** [comment]
Pushed a fix for the remove error @ltzmax 

The interaction error also appears for normal blacklists, I will leave that for another PR.
Ready to review

**Comment by ltzmax** [comment]
Looks good now, tested it on Tuesday at esport arena and have kept some small testing in between. Can't approve from phone but good to go whenever!

**Review by ltzmax — APPROVED** [review]
*insert jack cat gif here*

**Review by ltzmax — APPROVED** [review]
*insert jack cat gif here*

**Pull request merged**
