### PR TITLE
[Admin] Add user id to embed if ran from admin

### PR DESCRIPTION
**Pull request by flaree**

### CODE REVIEW

**Review by ltzmax — CHANGES_REQUESTED** [review]
Mostly work just fine. just one minus is when the wrong tradeid is used, it'd error with this. 
I believe an DoNotExist try except would do for now?
```py
bot-1  | 2024-08-09 20:52:20 ERROR    ballsdex.core.bot Error in slash command trade
bot-1  | Traceback (most recent call last):
bot-1  |   File "/usr/local/lib/python3.12/site-packages/discord/app_commands/commands.py", line 857, in _do_call
bot-1  |     return await self._callback(self.binding, interaction, **params)  # type: ignore
bot-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bot-1  |   File "/code/ballsdex/packages/admin/cog.py", line 1549, in trade_info
bot-1  |     trade = await Trade.get(id=pk).prefetch_related("player1", "player2")
bot-1  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bot-1  |   File "/usr/local/lib/python3.12/site-packages/tortoise/queryset.py", line 1074, in _execute
bot-1  |     raise DoesNotExist(self.model)
bot-1  | tortoise.exceptions.DoesNotExist: Object "Trade" does not exist
```

**Comment by flaree** [comment]
> Mostly work just fine. just one minus is when the wrong tradeid is used, it'd error with this. I believe an DoNotExist try except would do for now?
> 
> ```python
> bot-1  | 2024-08-09 20:52:20 ERROR    ballsdex.core.bot Error in slash command trade
> bot-1  | Traceback (most recent call last):
> bot-1  |   File "/usr/local/lib/python3.12/site-packages/discord/app_commands/commands.py", line 857, in _do_call
> bot-1  |     return await self._callback(self.binding, interaction, **params)  # type: ignore
> bot-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> bot-1  |   File "/code/ballsdex/packages/admin/cog.py", line 1549, in trade_info
> bot-1  |     trade = await Trade.get(id=pk).prefetch_related("player1", "player2")
> bot-1  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> bot-1  |   File "/usr/local/lib/python3.12/site-packages/tortoise/queryset.py", line 1074, in _execute
> bot-1  |     raise DoesNotExist(self.model)
> bot-1  | tortoise.exceptions.DoesNotExist: Object "Trade" does not exist
> ```

This should be addressed in a bug fix PR, unrelated to this.

**Comment by ltzmax** [comment]
Ah, okey!👍

**Comment by Isaax-yourman** [comment]
You should make a config to make the spawn time manual like every like minute or something or the way it is now I really would like this feature so me and my friends can have even more fun with the bot

**Pull request merged**
